const { chromium } = require("playwright");
const URL = "https://staging-music.ekaii.fr";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
(async () => {
  const browser = await chromium.launch({ channel: "chrome", args: ["--autoplay-policy=no-user-gesture-required", "--ignore-certificate-errors", "--host-resolver-rules=MAP *.ekaii.fr 127.0.0.1"] });
  const ctx = await browser.newContext({ extraHTTPHeaders: { "X-Ytm-Harness": "1" },  ignoreHTTPSErrors: true, viewport: { width: 1280, height: 900 } });
  const page = await ctx.newPage();
  page.on("pageerror", (e) => console.log("PAGEERROR", String(e).slice(0, 160)));
  await page.goto(URL + "/search/" + encodeURIComponent("daft punk") + "?filter=all", { waitUntil: "networkidle", timeout: 60000 });
  const rows = page.getByText(/Song\s*•/);
  console.log("song rows", await rows.count());
  await rows.first().click({ timeout: 8000 }); await sleep(3000);
  const kebabs = await page.evaluate(() => [...document.querySelectorAll("main .dd-button, main [aria-label], main [role=button]")].filter((e) => /option|menu/i.test(e.getAttribute("aria-label") || "") || e.classList.contains("dd-button")).slice(0, 6).map((e) => (e.getAttribute("aria-label") || "") + "|" + e.className.toString().slice(0, 30) + "|vis=" + (e.offsetParent !== null)));
  console.log("KEBABS", JSON.stringify(kebabs));
  const k = page.locator("main [aria-label=\"Plus d'options\"], main .dd-button").nth(1);
  console.log("kebab nth1 count", await page.locator("main [aria-label=\"Plus d'options\"], main .dd-button").count(), "visible", await k.isVisible().catch(() => false));
  await k.click({ timeout: 5000 }).catch((e) => console.log("kebab click err", e.message.slice(0, 80)));
  await sleep(800);
  const menu = await page.evaluate(() => [...document.querySelectorAll("[role=menu] *, .dropdown *, li, button")].filter((e) => e.offsetParent !== null && /Lire ensuite|Ajouter|file/i.test(e.textContent)).map((e) => e.tagName + ":" + e.textContent.trim().slice(0, 30)).slice(0, 6));
  console.log("MENU", JSON.stringify(menu));
  await page.getByText(/Ajouter à la file/i).first().click({ timeout: 5000 }).catch((e) => console.log("add click err", e.message.slice(0, 80)));
  await sleep(800);
  await page.keyboard.press("Escape");
  await page.locator("footer .now-playing img, footer img").first().click({ timeout: 5000 }).catch((e) => console.log("fs click err", e.message.slice(0, 60)));
  await sleep(1500);
  console.log("queue rows", await page.locator('[data-testid="queue-row"]').count(), "clear", await page.locator('[data-testid="queue-clear"]').count(), "clear visible", await page.locator('[data-testid="queue-clear"]').first().isVisible().catch(() => false));
  await page.screenshot({ path: "/e2e/out/probe-queue.png" });
  await browser.close();
})().catch((e) => { console.log("FATAL", String(e)); process.exit(1); });
