const { chromium } = require("playwright");
const URL = ((process.argv.find((a) => a.startsWith("--url=")) || "--url=https://staging-music.ekaii.fr").split("=").slice(1).join("=")).replace(/\/$/, "");
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
(async () => {
  const browser = await chromium.launch({ channel: process.env.PW_CHANNEL || undefined, args: ["--ignore-certificate-errors", "--host-resolver-rules=MAP *.ekaii.fr 127.0.0.1"] });
  const ctx = await browser.newContext({ extraHTTPHeaders: { "X-Ytm-Harness": "1" },  ignoreHTTPSErrors: true, viewport: { width: 1280, height: 800 } });
  const page = await ctx.newPage();
  const reqs = {};
  page.on("request", (r) => { const u = r.url().replace(URL, ""); reqs[u] = (reqs[u] || 0) + 1; });
  page.on("console", (m) => { if (m.type() === "error") console.log("CONSOLE", m.text().slice(0, 120)); });
  const t0 = Date.now();
  await page.goto(URL + "/explore/categorie-inexistante-xyz", { waitUntil: "domcontentloaded", timeout: 30000 });
  console.log("DCL after", Date.now() - t0, "ms");
  await sleep(6000);
  const nf = await page.locator('[data-testid="explore-not-found"]').count();
  console.log("NOT_FOUND_EL", nf, "URL", page.url());
  console.log("BODY", (await page.locator("body").innerText()).replace(/\s+/g, " ").slice(0, 160));
  const top = Object.entries(reqs).sort((a, b) => b[1] - a[1]).slice(0, 8);
  console.log("REQUESTS", JSON.stringify(top));
  await page.screenshot({ path: "/e2e/out/probe-explore.png" });
  await browser.close();
})().catch((e) => { console.log("FATAL", String(e)); process.exit(1); });
