const { chromium } = require("playwright");
const URL = ((process.argv.find((a) => a.startsWith("--url=")) || "--url=https://staging-music.ekaii.fr").split("=").slice(1).join("=")).replace(/\/$/, "");
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
(async () => {
  const browser = await chromium.launch({ channel: process.env.PW_CHANNEL || undefined, args: ["--ignore-certificate-errors", "--host-resolver-rules=MAP *.ekaii.fr 127.0.0.1"] });
  const ctx = await browser.newContext({ extraHTTPHeaders: { "X-Ytm-Harness": "1" },  ignoreHTTPSErrors: true, viewport: { width: 1280, height: 900 } });
  const page = await ctx.newPage();
  page.on("pageerror", (e) => console.log("PAGEERROR", String(e).slice(0, 140)));
  await page.goto(URL + "/library/albums", { waitUntil: "networkidle", timeout: 45000 });
  const links = await page.evaluate(() => [...document.querySelectorAll("a[href*='/release']")].slice(0, 4).map((a) => a.getAttribute("href")));
  console.log("ALBUM_LINKS", JSON.stringify(links));
  const card = page.locator("a[href*='/release?id=']").first();
  console.log("CARD_COUNT", await page.locator("a[href*='/release?id=']").count());
  await card.click({ timeout: 5000 });
  await sleep(4000);
  console.log("URL", page.url());
  console.log("KEEP", await page.locator('[data-testid="keep-offline"]').count(), "PLAYALL", await page.locator('[data-testid="play-all"]').count());
  console.log("BODY", (await page.locator("body").innerText()).replace(/\s+/g, " ").slice(0, 240));
  await page.screenshot({ path: "/e2e/out/probe-keep.png" }).catch(() => {});
  await browser.close();
})().catch((e) => { console.log("FATAL", String(e)); process.exit(1); });
